version: '3.8'

services:
  web:
    build: .
    container_name: web_design-web-1
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=web_design.settings
      - GUNICORN_CMD_ARGS=--workers=3 --bind=0.0.0.0:8000
    command: gunicorn web_design.wsgi:application
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: web_design-nginx-1
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
